import { describe, expect, test } from 'bun:test';
import { asyncTreeDisk } from './fakes.test.ts';
import { ProjectIndex } from './project.ts';

function withIndex(files: Record<string, string>) {
  const tree = asyncTreeDisk(files);
  return { index: new ProjectIndex(tree.disk), tree };
}

describe('sourceFiles', () => {
  test('reads source files and skips tests, dot folders, installed, built, generated, ignored, and given files', async () => {
    const code = 'export function a() {}';
    const { index } = withIndex({
      '/repo/.gitignore': '# comment\n/local.ts\ncache/\n**/*.snap.ts\n!keep.ts\nsrc/legacy/*.js\n',
      '/repo/src/a.ts': code,
      '/repo/src/deep/b.py': 'def b():\n    pass',
      '/repo/src/a.test.ts': code,
      '/repo/src/__tests__/helper.ts': code,
      '/repo/src/changed.ts': code,
      '/repo/.git/x.ts': code,
      '/repo/node_modules/x/index.js': code,
      '/repo/vendor/x.go': code,
      '/repo/dist/a.js': code,
      '/repo/src/a.min.js': code,
      '/repo/src/types.d.ts': code,
      '/repo/src/api.pb.go': code,
      '/repo/src/schema.ts': `// Code generated by x. DO NOT EDIT.\n${code}`,
      '/repo/local.ts': code,
      '/repo/src/local.ts': code,
      '/repo/cache/a.ts': code,
      '/repo/src/ui/button.snap.ts': code,
      '/repo/src/legacy/old.js': code,
      '/repo/src/legacy/keep/new.js': code,
      '/repo/README.md': '# readme',
    });
    expect((await index.sourceFiles(new Set(['/repo/src/changed.ts']))).map(file => file.path).sort()).toEqual([
      '/repo/src/a.ts',
      '/repo/src/deep/b.py',
      '/repo/src/legacy/keep/new.js',
      '/repo/src/local.ts',
    ]);
  });

  test('skips very large files', async () => {
    const { index } = withIndex({ '/repo/big.ts': 'x'.repeat(200_001), '/repo/ok.ts': 'x' });
    expect((await index.sourceFiles(new Set())).map(file => file.path)).toEqual(['/repo/ok.ts']);
  });

  test('stops at two thousand files', async () => {
    const files: Record<string, string> = {};
    for (let i = 0; i < 2100; i += 1) files[`/repo/src/a${i}.ts`] = 'export const a = 1';
    const { index } = withIndex(files);
    expect((await index.sourceFiles(new Set()))).toHaveLength(2000);
  });

  test('stops listing at twenty thousand entries', async () => {
    const files: Record<string, string> = {};
    for (let i = 0; i < 20_005; i += 1) files[`/repo/data${i}.txt`] = 'x';
    files['/repo/src/late.ts'] = 'export const a = 1';
    const { index, tree } = withIndex(files);
    expect(await index.sourceFiles(new Set())).toEqual([]);
    expect(tree.listCalls).toHaveLength(1);
  });
});

describe('relatedTests', () => {
  test('finds tests that import or are named for the file, the way contextFor maps a test to its code', async () => {
    const { index } = withIndex({
      '/repo/src/price.ts': 'export function total() {}',
      '/repo/src/price.test.ts': 'test(\'x\', () => {})',
      '/repo/src/__tests__/price.ts': 'test(\'y\', () => {})',
      '/repo/tests/cart.spec.ts': 'import { total } from \'../src/price.js\';',
      '/repo/tests/other.test.ts': 'import { tax } from \'../src/tax\';',
      '/repo/src/tax.ts': 'export function tax() {}',
      '/repo/py/test_price.py': 'from price import total',
      '/repo/py/price.py': 'def total():\n    pass',
    });
    expect((await index.relatedTests('src/price.ts')).map(file => file.path).sort()).toEqual([
      '/repo/src/__tests__/price.ts',
      '/repo/src/price.test.ts',
      '/repo/tests/cart.spec.ts',
    ]);
    expect((await index.relatedTests('/repo/py/price.py')).map(file => file.path)).toEqual(['/repo/py/test_price.py']);
  });

  test('skips installed and ignored tests, and stops at ten', async () => {
    const files: Record<string, string> = {
      '/repo/.gitignore': 'old/\n',
      '/repo/src/a.ts': 'export const a = 1',
      '/repo/node_modules/x/a.test.ts': 'import { a } from \'../../src/a\';',
      '/repo/old/a.test.ts': 'import { a } from \'../src/a\';',
    };
    for (let i = 0; i < 12; i += 1) files[`/repo/tests/a${i}.test.ts`] = 'import { a } from \'../src/a\';';
    const found = (await withIndex(files).index.relatedTests('src/a.ts')).map(file => file.path);
    expect(found).toHaveLength(10);
    expect(found.every(path => path.startsWith('/repo/tests/'))).toBe(true);
  });
});

describe('docSections', () => {
  test('returns the markdown section that names a function as a whole word, and skips instruction files and changelogs', async () => {
    const { index } = withIndex({
      '/repo/README.md': '# App\n\nIntro.\n\n## Retry\n\nCall `retry` to run a call again.\n\n## Other\n\nretryCount is unrelated.\n',
      '/repo/docs/guide.mdx': 'Use retry() for flaky calls.\n',
      '/repo/AGENTS.md': 'retry must stay small.\n',
      '/repo/docs/CHANGELOG.md': 'retry was added.\n',
      '/repo/node_modules/x/README.md': 'retry\n',
    });
    expect(await index.docSections(['retry'])).toEqual([
      { path: '/repo/README.md', line: 7, name: 'retry', text: '## Retry\n\nCall `retry` to run a call again.' },
      { path: '/repo/docs/guide.mdx', line: 1, name: 'retry', text: 'Use retry() for flaky calls.' },
    ]);
  });

  test('stops at five sections', async () => {
    const files: Record<string, string> = {};
    for (let i = 0; i < 8; i += 1) files[`/repo/docs/d${i}.md`] = `# D${i}\n\nretry here.\n`;
    expect(await withIndex(files).index.docSections(['retry'])).toHaveLength(5);
  });

  test('leaves markdown out of source files and related tests', async () => {
    const { index } = withIndex({
      '/repo/src/a.ts': 'export function a() {}',
      '/repo/src/a.md': 'export function a() {}',
      '/repo/tests/README.md': 'import { a } from \'../src/a\';',
    });
    expect((await index.sourceFiles(new Set())).map(file => file.path)).toEqual(['/repo/src/a.ts']);
    expect(await index.relatedTests('src/a.ts')).toEqual([]);
  });
});

describe('freshness', () => {
  test('re-reads a file the same call changed after it is marked stale', async () => {
    const { index, tree } = withIndex({ '/repo/src/a.ts': 'export const a = 1' });
    expect((await index.sourceFiles(new Set()))[0]?.text).toBe('export const a = 1');
    const reads = tree.readCalls.length;
    // An untouched file is served from the cache, not re-read.
    expect((await index.sourceFiles(new Set()))[0]?.text).toBe('export const a = 1');
    expect(tree.readCalls.length).toBe(reads);
    tree.write('/repo/src/a.ts', 'export const a = 2');
    index.markStale(['/repo/src/a.ts']);
    expect((await index.sourceFiles(new Set()))[0]?.text).toBe('export const a = 2');
  });

  test('re-reads when the stat changes even without a mark', async () => {
    const { index, tree } = withIndex({ '/repo/src/a.ts': 'export const a = 1' });
    expect((await index.sourceFiles(new Set()))[0]?.text).toBe('export const a = 1');
    tree.write('/repo/src/a.ts', 'export const a = 2');
    // A stat change is noticed on its own.
    index.markStale(['/repo/src/other.ts']);
    expect((await index.sourceFiles(new Set()))[0]?.text).toBe('export const a = 2');
  });

  test('a new file appears after the listing is marked stale', async () => {
    const { index, tree } = withIndex({ '/repo/src/a.ts': 'export const a = 1' });
    expect((await index.sourceFiles(new Set())).map(file => file.path)).toEqual(['/repo/src/a.ts']);
    tree.write('/repo/src/b.ts', 'export const b = 2');
    expect((await index.sourceFiles(new Set())).map(file => file.path)).toEqual(['/repo/src/a.ts']);
    index.markListingStale();
    expect((await index.sourceFiles(new Set())).map(file => file.path).sort()).toEqual(['/repo/src/a.ts', '/repo/src/b.ts']);
  });
});

describe('one walk', () => {
  test('several views share a single listing', async () => {
    const { index, tree } = withIndex({
      '/repo/src/a.ts': 'export function a() {}',
      '/repo/src/a.test.ts': 'import { a } from \'./a\';\ntest(\'x\', () => {})',
      '/repo/README.md': '# App\n\nUse `a` here.\n',
    });
    await index.sourceFiles(new Set());
    await index.relatedTests('src/a.ts');
    await index.docSections(['a']);
    await index.sourceFiles(new Set());
    const dirs = tree.listCalls.slice().sort();
    // One call per folder: the root and src. No view lists twice.
    expect(dirs).toEqual(['/repo', '/repo/src']);
  });
});
