import { describe, expect, test } from 'bun:test';
import { asyncTreeDisk, deps, jsonResponse, treeDisk } from './fakes.test.ts';
import { ProjectIndex } from './project.ts';
import { checkReuse } from './reuse.ts';
import { type Settings } from './settings.ts';

describe('reuse check', () => {
  const TO_ISO_DAY = 'export function toIsoDay(date: Date): string {\n  return date.toISOString().slice(0, 10);\n}';
  const FORMAT_DAY = 'export function formatDay(day: Date): string {\n  // the ISO day\n  return day.toISOString().slice(0, 10);\n}';
  const project: Record<string, string> = {
    '/repo/.gitignore': '# local\ntmp/\n/local.ts\n**/*.snap.ts\n',
    '/repo/src/date.ts': `import { pad } from './pad';\n\n${TO_ISO_DAY}\n`,
    '/repo/src/math.ts': 'export function sum(values: number[]): number {\n  let total = 0;\n  for (const value of values) total += value;\n  return total;\n}\n',
    '/repo/src/date.test.ts': `${TO_ISO_DAY}\n`,
    '/repo/node_modules/lib/date.ts': `${TO_ISO_DAY}\n`,
    '/repo/dist/date.js': `${TO_ISO_DAY}\n`,
    '/repo/.cache/date.ts': `${TO_ISO_DAY}\n`,
    '/repo/src/api.generated.ts': `${TO_ISO_DAY}\n`,
    '/repo/src/schema.ts': `// @generated by a tool\n${TO_ISO_DAY}\n`,
    '/repo/tmp/date.ts': `${TO_ISO_DAY}\n`,
    '/repo/local.ts': `${TO_ISO_DAY}\n`,
    '/repo/src/day.snap.ts': `${TO_ISO_DAY}\n`,
  };

  interface ReuseBody {
    state: {
      purpose: string;
      user_messages?: string[];
      new_code: { path: string; name: string; code: string }[];
      existing: { path: string; line: number; name: string; code: string }[];
    };
    questions: Record<string, { type: string; instructions: string; criteria: { true: string; false: string } }>;
  }

  function run(tool: string, args: unknown, answers: Record<string, unknown>, options: { files?: Record<string, string>; userMessages?: string[]; settings?: Partial<Settings>; fail?: boolean } = {}) {
    const bodies: ReuseBody[] = [];
    const tree = treeDisk(options.files ?? project);
    const async = asyncTreeDisk(options.files ?? project);
    const used = deps((_url, init) => {
      bodies.push(JSON.parse(String(init.body)) as ReuseBody);
      if (options.fail) return Promise.reject(new Error('offline'));
      return Promise.resolve(jsonResponse({ answers }));
    }, options.settings ?? { key: 'ts_secret' }, tree.disk);
    used.userMessages = options.userMessages;
    used.project = new ProjectIndex(async.disk);
    return { result: checkReuse(tool, args, used), bodies, used, reads: async.readCalls };
  }

  const write = { filePath: 'src/format.ts', content: FORMAT_DAY };
  const sure = { type: 'noul', noul: 0.9, confidence: 0.9 };

  test('sends the new function and the closest existing code, skipping tests, installed, built, generated, and ignored files', async () => {
    const asked = run('write', write, {});
    expect(await asked.result).toBeUndefined();
    expect(asked.bodies).toHaveLength(1);
    const body = asked.bodies[0];
    expect(body?.state.new_code).toEqual([{ path: 'src/format.ts', name: 'formatDay', code: 'export function formatDay(day: Date): string {\n\n  return day.toISOString().slice(0, 10);\n}' }]);
    expect(body?.state.existing).toEqual([{ path: 'src/date.ts', line: 3, name: 'toIsoDay', code: TO_ISO_DAY }]);
    expect(body?.state.user_messages).toBeUndefined();
    expect(body?.questions).toEqual({
      r0_x0_duplicates: {
        type: 'noul',
        instructions: 'Does the new function in `new_code[0]` do the same job as the existing function in `existing[0]`, so the existing one should be reused instead?',
        criteria: {
          true: 'The existing function already does what the new one does, for the same kind of input, so the new code could call it, or call it with a small extra parameter, instead of repeating its logic.',
          false: 'They do different jobs or work on different data, or only share names, types, or a common pattern such as a loop or a map. A new function that calls the existing one is not a copy.',
        },
      },
    });
    for (const skipped of ['/repo/src/date.test.ts', '/repo/node_modules/lib/date.ts', '/repo/dist/date.js', '/repo/.cache/date.ts', '/repo/src/api.generated.ts', '/repo/tmp/date.ts', '/repo/local.ts', '/repo/src/day.snap.ts']) {
      expect([skipped, asked.reads.includes(skipped)]).toEqual([skipped, false]);
    }
  });

  test('notes a sure repeat with the existing path and line, the new code, and what to reuse', async () => {
    const result = await run('write', write, { r0_x0_duplicates: sure }).result;
    expect(result).toBe([
      'Jevy note: this change was made, but it may repeat code that already exists.',
      '- src/format.ts, function "formatDay"',
      '  Duplicate code: It repeats what existing code already does.',
      '  existing: src/date.ts:3 export function toIsoDay(date: Date): string {',
      '  new: export function formatDay(day: Date): string {',
      '  next: Reuse toIsoDay from src/date.ts instead of a new copy. If the new one must differ, keep it or ask the user.',
      'Check it, and fix it if the note is right.',
    ].join('\n'));
  });

  test('never blocks, and says nothing unless Jev is sure', async () => {
    expect(await run('write', write, { r0_x0_duplicates: { type: 'noul', noul: 0.79 } }).result).toBeUndefined();
    expect(await run('write', write, { r0_x0_duplicates: { type: 'noul', noul: 0.95, confidence: 0.6 } }).result).toBeUndefined();
    expect(await run('write', write, { r0_x0_duplicates: { type: 'noul', noul: 0.95 } }).result).toContain('Duplicate code');
  });

  test('does not call Jev or read the config without a new function', async () => {
    const cases: [string, unknown][] = [
      ['edit', { filePath: 'src/date.ts', oldString: '  return date.toISOString().slice(0, 10);', newString: '  return date.toISOString().slice(0, 10).trim();' }],
      ['write', { filePath: 'src/format.test.ts', content: FORMAT_DAY }],
      ['write', { filePath: 'docs/format.md', content: FORMAT_DAY }],
      ['write', { filePath: 'node_modules/x/format.ts', content: FORMAT_DAY }],
      ['write', { filePath: 'src/const.ts', content: 'export const DAY = 86_400_000;' }],
      ['bash', { command: 'git status' }],
    ];
    for (const [tool, args] of cases) {
      const asked = run(tool, args, { r0_x0_duplicates: sure });
      expect(await asked.result).toBeUndefined();
      expect(asked.bodies).toHaveLength(0);
      expect(asked.used.loads).toBe(0);
    }
  });

  test('skips code the same call removes or moves', async () => {
    const moved = [
      '*** Begin Patch',
      '*** Update File: src/date.ts',
      '@@',
      ...TO_ISO_DAY.split('\n').map(line => `-${line}`),
      '*** Add File: src/day.ts',
      ...TO_ISO_DAY.split('\n').map(line => `+${line}`),
      '*** End Patch',
    ].join('\n');
    const move = run('apply_patch', { patchText: moved }, { r0_x0_duplicates: sure });
    expect(await move.result).toBeUndefined();
    expect(move.bodies).toHaveLength(0);
    // Another copy exists, so only the refactor rule keeps this from being asked.
    const files = { ...project, '/repo/src/time.ts': 'export function isoDate(date: Date): string {\n  return date.toISOString().slice(0, 10);\n}\n' };
    const renamed = run('edit', { filePath: 'src/date.ts', oldString: TO_ISO_DAY, newString: FORMAT_DAY }, { r0_x0_duplicates: sure }, { files });
    expect(await renamed.result).toBeUndefined();
    expect(renamed.bodies).toHaveLength(0);
    const replaced = { ...project, '/repo/src/other.ts': 'export function isoDay(when: Date): string {\n  const text = when.toISOString();\n  return text.slice(0, 10);\n}\n' };
    const patchText = [
      '*** Begin Patch',
      '*** Update File: src/other.ts',
      '@@',
      '-export function isoDay(when: Date): string {',
      '-  const text = when.toISOString();',
      '-  return text.slice(0, 10);',
      '-}',
      '+export function weekday(when: Date): number {',
      '+  return when.getDay();',
      '+}',
      '*** Add File: src/format.ts',
      ...FORMAT_DAY.split('\n').map(line => `+${line}`),
      '*** End Patch',
    ].join('\n');
    const asked = run('apply_patch', { patchText }, {}, { files: replaced });
    await asked.result;
    expect(asked.bodies[0]?.state.existing.map(item => item.name)).toEqual(['toIsoDay']);
  });

  test('does not call Jev when no existing code shares enough words', async () => {
    const asked = run('write', { filePath: 'src/color.ts', content: 'export function mixColors(red: Rgb, blue: Rgb): Rgb {\n  return blend(red, blue);\n}' }, {});
    expect(await asked.result).toBeUndefined();
    expect(asked.bodies).toHaveLength(0);
  });

  test('compares with other functions in the same file, as it was before the write', async () => {
    const files = { '/repo/src/format.ts': `${TO_ISO_DAY}\n` };
    const asked = run('write', { filePath: 'src/format.ts', content: `${TO_ISO_DAY}\n\n${FORMAT_DAY}\n` }, {}, { files });
    await asked.result;
    expect(asked.bodies[0]?.state.new_code.map(item => item.name)).toEqual(['formatDay']);
    expect(asked.bodies[0]?.state.existing).toEqual([{ path: 'src/format.ts', line: 1, name: 'toIsoDay', code: TO_ISO_DAY }]);
  });

  test('allows a separate copy the user asked for, with the shared user-intent question', async () => {
    const asked = run('write', write, { r0_x0_duplicates: sure, r0_user_asked: { type: 'noul', noul: 0.6 } }, { userMessages: ['Write a new formatDay, do not touch date.ts.'] });
    expect(await asked.result).toBeUndefined();
    expect(asked.bodies[0]?.state.user_messages).toEqual(['Write a new formatDay, do not touch date.ts.']);
    expect(asked.bodies[0]?.questions.r0_user_asked?.instructions).toBe('Do the user\'s messages in `user_messages` ask for a separate function in `new_code[0]` instead of reusing existing code?');
    expect(asked.bodies[0]?.questions.r0_user_asked?.criteria.false).toBe('The user does not ask for it. Asking to fix a failure or to make the tests pass does not count.');
    expect(asked.used.logs).toEqual(['src/format.ts: the user asked for a separate formatDay. No reuse note was added.']);
    const notAsked = run('write', write, { r0_x0_duplicates: sure, r0_user_asked: { type: 'noul', noul: 0.2 } }, { userMessages: ['Format the day in the header.'] });
    expect(await notAsked.result).toContain('Reuse toIsoDay from src/date.ts');
  });

  test('adds nothing without a key, with an unreadable config, or when TypeSafe fails', async () => {
    const noKey = run('write', write, { r0_x0_duplicates: sure }, { settings: { key: '' } });
    expect(await noKey.result).toBeUndefined();
    expect(noKey.bodies).toHaveLength(0);
    const bad = run('write', write, { r0_x0_duplicates: sure }, { settings: { key: 'ts_secret', error: 'bad config' } });
    expect(await bad.result).toBeUndefined();
    expect(bad.bodies).toHaveLength(0);
    const down = run('write', write, {}, { fail: true });
    expect(await down.result).toBeUndefined();
    expect(down.used.logs).toEqual(['TypeSafe request failed. No reuse note was added.']);
  });

  test('asks about at most five new functions and three candidates each', async () => {
    const files: Record<string, string> = {};
    for (let n = 0; n < 5; n += 1) files[`/repo/src/day${n}.ts`] = `${TO_ISO_DAY}\n`;
    const content = Array.from({ length: 7 }, (_, n) => `export function formatDay${n}(day: Date): string {\n  return day.toISOString().slice(0, 10);\n}`).join('\n');
    const asked = run('write', { filePath: 'src/format.ts', content }, {}, { files });
    await asked.result;
    const body = asked.bodies[0];
    expect(body?.state.new_code).toHaveLength(5);
    const ids = Object.keys(body?.questions ?? {});
    expect(ids).toHaveLength(15);
    for (let n = 0; n < 5; n += 1) expect(ids.filter(id => id.startsWith(`r${n}_`))).toHaveLength(3);
  });
});
